### ISSUE TITLE
Cannot install on Ubuntu

### ISSUE THREAD

**Issue by CHJ85** [javiermisol/m64py-0.2.5#1]
I'm trying to run m64py on Ubuntu. getting this error:
Traceback (most recent call last):
  File "/usr/local/bin/m64py", line 4, in <module>
    __import__('pkg_resources').run_script('m64py==0.2.5', 'm64py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'm64py==0.2.5' distribution was not found and is required by the application

The error message indicates that the Python package m64py==0.2.5 is not found.  But that makes no sense, because I moved the content of usr file to its respective places

**Comment by javiermisol** [comment]
Hola y gracias por la incidencia.

Al parecer faltan librerías por instalar.

He creado de nuevo el paquete incorporando las librerías que faltan e intentar ver si funciona.


Hello and thanks for the incident.

Apparently there are missing libraries to install.

I have recreated the package again incorporating the missing libraries and try to see if it works.
